name: gswatcher
base: core24
grade: stable
confinement: strict
adopt-info: gswatcher

platforms:
  amd64:
  arm64:

slots:
  gswatcher:
    interface: dbus
    bus: session
    name: io.github.lxndr.gswatcher

apps:
  gswatcher:
    extensions:
      - gnome
    command: usr/bin/gswatcher
    desktop: usr/share/applications/io.github.lxndr.gswatcher.desktop
    common-id: io.github.lxndr.gswatcher
    plugs:
      - network
    environment:
      GSW_GAME_ICONS_DIR: $SNAP_DATA/nonfree-icons/games

parts:
  vala:
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/vala.git
    source-type: git
    source-tag: 0.56.18
    source-depth: 1
    build-packages:
      - autoconf-archive
      - flex
      - bison
    autotools-configure-parameters:
      - --prefix=/usr
    prime:
      - -**
  gswatcher:
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Diso-flags-dir-name=iso-flags-png-320x240
    parse-info:
      - usr/share/metainfo/io.github.lxndr.gswatcher.metainfo.xml
    build-packages:
      - imagemagick
      - liblua5.4-dev
      - libgeoip-dev
    stage-packages:
      - iso-flags-png-320x240
  lua:
    plugin: nil
    stage-packages:
      - liblua5.4-0
    stage:
      - usr/lib/*/liblua5.4.so.*
  geoip:
    plugin: nil
    override-pull: |
      curl -sSLO https://sources.archlinux.org/other/packages/geoip-database/20250129/GeoIPCity.dat.gz
      echo "bf2e8452642514ca64e2ba6aace3c3bf08be7b79f0d994fd98d68dc87b395ce4 GeoIPCity.dat.gz" | sha256sum -c
    override-build: |
      mkdir -p "$CRAFT_PART_INSTALL/usr/share/GeoIP"
      gzip -dc GeoIPCity.dat.gz > "$CRAFT_PART_INSTALL/usr/share/GeoIP/GeoIPCity.dat"
    build-packages:
      - curl
    stage-packages:
      - libgeoip1
    stage:
      - usr/lib/*/libGeoIP.so.*
      - usr/share/GeoIP/GeoIPCity.dat
  nonfree:
    plugin: nil
    stage-packages:
      - wget

hooks:
  post-refresh:
    plugs:
      - network
