#!/bin/sh

wget -P "$TMPDIR" https://github.com/lxndr/gswatcher-nonfree-icons/releases/download/v1.7.1/nonfree-icons.tar.gz
tar -xf "$TMPDIR/nonfree-icons.tar.gz" -C $SNAP_DATA
rm "$TMPDIR/nonfree-icons.tar.gz"

